const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Pups collection and inserts the Pups below

mongoose.connect(
  process.env.MONGODB_URI ||
  // "mongodb://localhost/pupsplay"
  "mongodb://localhost/pupsplayTesting"
);

const PupSeed = [
  {
    ownername: "Liz S",
    email: "liz@liz.com",
    passsword: "Thisisapassword123",
    pupname: "Skeletor",
    breed: "Greyhound",
    sex: "female",
    spayNeutered: "yes",
    age: 12,
    size: "medium",
    location: 60647,
    bio: "Skeletor is a retired racing dog. She used to be fast but now she's just a big couch potato.",
    date: new Date(Date.now())
  },
  {
    ownername: "Alfredo C",
    email: "alfredo@alfredo.com",
    passsword: "Thisisapassword123",
    pupname: "Choco",
    breed: "Labrador Retriever",
    sex: "male",
    spayNeutered: "yes",
    age: 3,
    size: "large",
    location: 60613,
    bio: "Choco is a sweetheart that loves to run and play.",
    date: new Date(Date.now())
  },
  {
    ownername: "Carolyn R",
    email: "carolyn@carolyn.com",
    passsword: "Thisisapassword123",
    pupname: "Tache",
    breed: "Dalmation",
    sex: "male",
    spayNeutered: "yes",
    age: 2,
    size: "large",
    location: 92116,
    bio: "Tache eats everything.",
    date: new Date(Date.now())
  },
  {
    ownername: "Tony P",
    email: "tony@tony.com",
    passsword: "Thisisapassword123",
    pupname: "Fido",
    breed: "Mixed breed",
    sex: "female",
    spayNeutered: "yes",
    age: 8,
    size: "medium",
    location: 60626,
    bio: "Fido is a rescue and the best dog that ever lived.",
    date: new Date(Date.now())
  },
];

const BreedSeed = [
  { breedname: "Mixed Breed" },
  { breedname: "Affenpinscher" },
  { breedname: "Afghan Hound" },
  { breedname: "Airedale Terrier" },
  { breedname: "Akita" },
  { breedname: "Alaskan Malamute" },
  { breedname: "American English Coonhound" },
  { breedname: "American Eskimo Dog" },
  { breedname: "American Foxhound" },
  { breedname: "American Hairless Terrier" },
  { breedname: "American Staffordshire Terrier" },
  { breedname: "Anatolian Shepherd Dog" },
  { breedname: "Australian Cattle Dog" },
  { breedname: "Australian Shepherd" },
  { breedname: "Australian Terrier" },
  { breedname: "Basenji" },
  { breedname: "Basset Hound" },
  { breedname: "Beagle" },
  { breedname: "Bearded Collie" },
  { breedname: "Beauceron" },
  { breedname: "Bedlington Terrier" },
  { breedname: "Belgian Malinoi" },
  { breedname: "Belgian Sheepdog" },
  { breedname: "Belgian Tervuren" },
  { breedname: "Bergamasco Sheepdog" },
  { breedname: "Berger Picard" },
  { breedname: "Bernese Mountain Dog" },
  { breedname: "Bichons Frise" },
  { breedname: "Black and Tan Coonhound" },
  { breedname: "Black Russian Terrier" },
  { breedname: "Bloodhound" },
  { breedname: "Bluetick Coonhound" },
  { breedname: "Boerboel" },
  { breedname: "Border Collie" },
  { breedname: "Border Terrier" },
  { breedname: "Borzoi" },
  { breedname: "Boston Terrier" },
  { breedname: "Bouviers des Flandres" },
  { breedname: "Boxer" },
  { breedname: "Briard" },
  { breedname: "Brittany" },
  { breedname: "Brussels Griffon" },
  { breedname: "Bull Terrier" },
  { breedname: "Bulldog" },
  { breedname: "Bullmastiff" },
  { breedname: "Cairn Terrier" },
  { breedname: "Canaan Dog" },
  { breedname: "Cane Corso" },
  { breedname: "Cardigan Welsh Corgi" },
  { breedname: "Cavalier King Charles Spaniel" },
  { breedname: "Cesky Terrier" },
  { breedname: "Chihuahua" },
  { breedname: "Chinese Crested" },
  { breedname: "Chinese Shar-Pei" },
  { breedname: "Chinook" },
  { breedname: "Chow Chow" },
  { breedname: "Cirneco dell’Etna" },
  { breedname: "Collie" },
  { breedname: "Coton de Tulear" },
  { breedname: "Dachshund" },
  { breedname: "Dalmatian" },
  { breedname: "Dandie Dinmont Terrier" },
  { breedname: "Doberman Pinscher" },
  { breedname: "Dogues de Bordeaux" },
  { breedname: "English Foxhound" },
  { breedname: "English Toy Spaniel" },
  { breedname: "Entlebucher Mountain Dog" },
  { breedname: "Finnish Lapphund" },
  { breedname: "Finnish Spitz" },
  { breedname: "Fox Terriers (Smooth)" },
  { breedname: "Fox Terriers (Wire)" },
  { breedname: "French Bulldog" },
  { breedname: "German Pinscher" },
  { breedname: "German Shepherd Dog" },
  { breedname: "Giant Schnauzer" },
  { breedname: "Glen of Imaal Terrier" },
  { breedname: "Great Dane" },
  { breedname: "Great Pyrenee" },
  { breedname: "Greater Swiss Mountain Dog" },
  { breedname: "Greyhound" },
  { breedname: "Harrier" },
  { breedname: "Havanese" },
  { breedname: "Ibizan Hound" },
  { breedname: "Icelandic Sheepdog" },
  { breedname: "Irish Terrier" },
  { breedname: "Irish Wolfhound" },
  { breedname: "Italian Greyhound" },
  { breedname: "Japanese Chin" },
  { breedname: "Keeshonden" },
  { breedname: "Kerry Blue Terrier" },
  { breedname: "Komondorok" },
  { breedname: "Kuvaszok" },
  { breedname: "Lagotti Romagnoli" },
  { breedname: "Lakeland Terrier" },
  { breedname: "Leonberger" },
  { breedname: "Lhasa Apso" },
  { breedname: "Lowchen" },
  { breedname: "Maltese" },
  { breedname: "Manchester Terrier" },
  { breedname: "Mastiff" },
  { breedname: "Miniature American Shepherd" },
  { breedname: "Miniature Bull Terrier" },
  { breedname: "Miniature Pinscher" },
  { breedname: "Miniature Schnauzer" },
  { breedname: "Neapolitan Mastiff" },
  { breedname: "Newfoundland" },
  { breedname: "Norfolk Terrier" },
  { breedname: "Norwegian Buhund" },
  { breedname: "Norwegian Elkhound" },
  { breedname: "Norwegian Lundehund" },
  { breedname: "Norwich Terrier" },
  { breedname: "Old English Sheepdog" },
  { breedname: "Otterhound" },
  { breedname: "Papillon" },
  { breedname: "Parson Russell Terrier" },
  { breedname: "Pekingese" },
  { breedname: "Pembroke Welsh Corgi" },
  { breedname: "Petits Bassets Griffons Vendeen" },
  { breedname: "Pharaoh Hound" },
  { breedname: "Plott" },
  { breedname: "Pointers (German Shorthaired)" },
  { breedname: "Pointers (German Wirehaired)" },
  { breedname: "Pointer" },
  { breedname: "Polish Lowland Sheepdog" },
  { breedname: "Pomeranian" },
  { breedname: "Poodle" },
  { breedname: "Portuguese Podengo Pequeno" },
  { breedname: "Portuguese Water Dog" },
  { breedname: "Pug" },
  { breedname: "Puli" },
  { breedname: "Pumi" },
  { breedname: "Pyrenean Shepherd" },
  { breedname: "Rat Terrier" },
  { breedname: "Redbone Coonhound" },
  { breedname: "Retrievers (Chesapeake Bay)" },
  { breedname: "Retrievers (Curly-Coated)" },
  { breedname: "Retrievers (Flat-Coated)" },
  { breedname: "Retrievers (Golden)" },
  { breedname: "Retrievers (Labrador)" },
  { breedname: "Retrievers (Nova Scotia Duck Tolling)" },
  { breedname: "Rhodesian Ridgeback" },
  { breedname: "Rottweiler" },
  { breedname: "Russell Terrier" },
  { breedname: "Saluki" },
  { breedname: "Samoyed" },
  { breedname: "Schipperke" },
  { breedname: "Scottish Deerhound" },
  { breedname: "Scottish Terrier" },
  { breedname: "Sealyham Terrier" },
  { breedname: "Setters (English)" },
  { breedname: "Setters (Gordon)" },
  { breedname: "Setters (Irish Red and White)" },
  { breedname: "Setters (Irish)" },
  { breedname: "Shetland Sheepdog" },
  { breedname: "Shiba Inu" },
  { breedname: "Shih Tzu" },
  { breedname: "Siberian Huskie" },
  { breedname: "Silky Terrier" },
  { breedname: "Skye Terrier" },
  { breedname: "Sloughi" },
  { breedname: "Soft Coated Wheaten Terrier" },
  { breedname: "Spaniels (American Water)" },
  { breedname: "Spaniels (Boykin)" },
  { breedname: "Spaniels (Clumber)" },
  { breedname: "Spaniels (Cocker)" },
  { breedname: "Spaniels (English Cocker)" },
  { breedname: "Spaniels (English Springer)" },
  { breedname: "Spaniels (Field)" },
  { breedname: "Spaniels (Irish Water)" },
  { breedname: "Spaniels (Sussex)" },
  { breedname: "Spaniels (Welsh Springer)" },
  { breedname: "Spanish Water Dog" },
  { breedname: "Spinoni Italiani" },
  { breedname: "St. Bernard" },
  { breedname: "Staffordshire Bull Terrier" },
  { breedname: "Standard Schnauzer" },
  { breedname: "Swedish Vallhund" },
  { breedname: "Tibetan Mastiff" },
  { breedname: "Tibetan Spaniel" },
  { breedname: "Tibetan Terrier" },
  { breedname: "Toy Fox Terrier" },
  { breedname: "Treeing Walker Coonhound" },
  { breedname: "Vizsla" },
  { breedname: "Weimaraner" },
  { breedname: "Welsh Terrier" },
  { breedname: "West Highland White Terrier" },
  { breedname: "Whippet" },
  { breedname: "Wirehaired Pointing Griffon" },
  { breedname: "Wirehaired Vizsla" },
  { breedname: "Xoloitzcuintli" },
  { breedname: "Yorkshire Terrier" },
];

db.Pup
  .remove({})
  .then(() => db.Pup.collection.insertMany(PupSeed))
  .then(() => db.Breed.collection.insertMany(BreedSeed))
  .then(data => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
